---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: configuration play
  hosts: ami_2051294a
  user: ansible
  gather_facts: true

  tasks:
     - name: Hello User
       debug:
         msg: "Hello user!"
     - name: install the latest version of ntp
       yum: name=ntp state=latest

#     - name: install the latest version of Apache
#       yum: name=httpd state=latest
#     - name: Check NTP service
#       service: name=ntpd state=started
