---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: Only RHEL
  hosts: ami_2051294a
  user: ansible
  gather_facts: true

  tasks:
     - name: Hello User
       debug:
         msg: "Hello user!"

- name: Only Ubuntu
  hosts: ami_2d39803a
  user: ansible
  gather_facts: true

  tasks:
     - name: Update Packages
       apt: update_cache=yes
