---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: Only RHEL
  hosts: ami_2051294a
  user: ansible
  gather_facts: true

  tasks:
     - name: Hello User
       debug:
         msg: "Hello user!"

- name: Only Ubuntu
  hosts: ami_2d39803a
  remote_user: root
  gather_facts: true

  tasks:
     - name: Update Packages
       apt: update_cache=yes
       become: yes
       become_method: sudo
     - name: install the latest version of Apache
       apt: name=apache2 state=latest

- name: Only Ubuntu
  hosts: tag_node_3
  remote_user: root
  gather_facts: true

  tasks:
     - name: Stop Apache service
       service: name=apache2 state=stopped
