- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- hosts: all
  name: configuration play
  user: ec2-user
  gather_facts: true

  tasks:
     - name: Hello Message
      debug:
        msg: "Hello World!"
     
#     name: Check NTP service
#       service: name=ntpd state=started
