---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: configuration play
  hosts: ami_2051294a
  user: ec2-user
  gather_facts: true

  tasks:
     - name: Hello Message
       debug:
         msg: "Hello user!"
     
#     name: Check NTP service
#       service: name=ntpd state=started
